version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  test-formatting:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - run:
          command: |
            python -m pip install black
            python -m black --check src tests documentation

  build-and-test:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - run:
          command: |
            python -m pip install .
            python -m pip install tox
            python -m tox --skip-missing-interpreters

workflows:
  main:
    jobs:
      - test-formatting
      - build-and-test
